
package time.susu.ru;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TimeService", targetNamespace = "ru.susu.time", wsdlLocation = Settings.URL + "?WSDL")
public class TimeService
    extends Service
{

    private final static URL TIMESERVICE_WSDL_LOCATION;
    private final static WebServiceException TIMESERVICE_EXCEPTION;
    private final static QName TIMESERVICE_QNAME = new QName("ru.susu.time", "TimeService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL(Settings.URL + "?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TIMESERVICE_WSDL_LOCATION = url;
        TIMESERVICE_EXCEPTION = e;
    }

    public TimeService() {
        super(__getWsdlLocation(), TIMESERVICE_QNAME);
    }

    public TimeService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TIMESERVICE_QNAME, features);
    }

    public TimeService(URL wsdlLocation) {
        super(wsdlLocation, TIMESERVICE_QNAME);
    }

    public TimeService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TIMESERVICE_QNAME, features);
    }

    public TimeService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TimeService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Application
     */
    @WebEndpoint(name = "Application")
    public Application getApplication() {
        return super.getPort(new QName("ru.susu.time", "Application"), Application.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Application
     */
    @WebEndpoint(name = "Application")
    public Application getApplication(WebServiceFeature... features) {
        return super.getPort(new QName("ru.susu.time", "Application"), Application.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TIMESERVICE_EXCEPTION!= null) {
            throw TIMESERVICE_EXCEPTION;
        }
        return TIMESERVICE_WSDL_LOCATION;
    }

}
